name: Build and Push Docker Image to GAR

on:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GAR_REGION }}-docker.pkg.dev

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      # Step 2: Get version from pom.xml
      - name: Get version from pom.xml
        id: get_version
        run: |
           APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | xargs)
           echo "APP_VERSION=$APP_VERSION"  # Logs the version to make sure it's working
           echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV  # Make it available to later steps

      - name: Build Docker image
        run: |
          echo "docker build -t ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:$APP_VERSION -f devOps/Dockerfile ."
          docker build -t ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:$APP_VERSION -f devOps/Dockerfile .
          docker tag ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:$APP_VERSION \ 
                              ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:latest

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:$APP_VERSION          
          docker push ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy daftar-back \
            --image ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:$APP_VERSION \
            --platform managed \
            --region ${{ secrets.GAR_REGION }} \
            --allow-unauthenticated \
            --set-env-vars=SPRING_PROFILES_ACTIVE=prod \
            --memory=512Mi \
            --cpu=1 \
            --port=8080
