name: Build and Push Docker Image to GAR

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GAR_REGION }}-docker.pkg.dev

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:latest -f devOps/Dockerfile .


      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:latest          
          

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy daftar-back \
            --image ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-back:latest \
            --platform managed \
            --region ${{ secrets.GAR_REGION }} \
            --allow-unauthenticated \
            --memory=512Mi \
            --cpu=1